[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions."scheduled-push-morning"]
  schedule = "15 0 * * *"

[functions."scheduled-push-evening"]
  schedule = "20 9 * * *"

[functions."scheduled-bot-poll"]
  schedule = "*/1 * * * *"
